DROP TABLE IF EXISTS "NOTIFICATIONS" CASCADE;
DROP TABLE IF EXISTS "PAYMENTS" CASCADE;
DROP TABLE IF EXISTS "ORDER_STATUS_HISTORIES" CASCADE;
DROP TABLE IF EXISTS "ORDER_ITEMS" CASCADE;
DROP TABLE IF EXISTS "ORDERS" CASCADE;
DROP TABLE IF EXISTS "OUTLET_PAYMENT_METHODS" CASCADE;
DROP TABLE IF EXISTS "SERVICES" CASCADE;
DROP TABLE IF EXISTS "OUTLET_USERS" CASCADE;
DROP TABLE IF EXISTS "DISCOUNTS" CASCADE;
DROP TABLE IF EXISTS "SERVICE_CATEGORIES" CASCADE;
DROP TABLE IF EXISTS "OUTLETS" CASCADE;
DROP TABLE IF EXISTS "AUDIT_LOGS" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;
DROP TABLE IF EXISTS "CUSTOMERS" CASCADE;
DROP TABLE IF EXISTS "TENANTS" CASCADE;

DROP FUNCTION IF EXISTS update_timestamp_column() CASCADE;