// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Wenell09/lavendera-api/internal/auth/controller"
	"github.com/Wenell09/lavendera-api/internal/auth/repository"
	"github.com/Wenell09/lavendera-api/internal/auth/service"
	controller4 "github.com/Wenell09/lavendera-api/internal/discount/controller"
	repository4 "github.com/Wenell09/lavendera-api/internal/discount/repository"
	service4 "github.com/Wenell09/lavendera-api/internal/discount/service"
	controller3 "github.com/Wenell09/lavendera-api/internal/service/controller"
	repository3 "github.com/Wenell09/lavendera-api/internal/service/repository"
	service3 "github.com/Wenell09/lavendera-api/internal/service/service"
	controller2 "github.com/Wenell09/lavendera-api/internal/service_category/controller"
	repository2 "github.com/Wenell09/lavendera-api/internal/service_category/repository"
	service2 "github.com/Wenell09/lavendera-api/internal/service_category/service"
	"github.com/Wenell09/lavendera-api/internal/shared/applogger"
	"github.com/Wenell09/lavendera-api/internal/shared/appvalidator"
	"github.com/Wenell09/lavendera-api/internal/shared/config"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db := NewDB()
	authRepository := repository.NewAuthRepository(db)
	jwtConfig := config.NewJWTConfig()
	logger := applogger.NewLogger()
	authService := service.NewAuthService(authRepository, jwtConfig, logger)
	validate := appvalidator.NewValidator()
	authController := controller.NewAuthController(authService, validate, logger)
	serviceCategoryRepository := repository2.NewServiceCategoryRepository(db)
	serviceCategoryService := service2.NewServiceCategoryService(serviceCategoryRepository, logger)
	serviceCategoryController := controller2.NewServiceCategoryController(serviceCategoryService, validate)
	serviceRepository := repository3.NewServiceRepository(db)
	serviceService := service3.NewService(serviceRepository, logger, serviceCategoryRepository)
	serviceController := controller3.NewServiceController(serviceService, validate)
	discountRepository := repository4.NewDiscountRepository(db)
	discountService := service4.NewDiscountService(discountRepository, logger)
	discountController := controller4.NewDiscountController(discountService, validate)
	engine := NewRouter(authController, serviceCategoryController, serviceController, discountController, jwtConfig, logger)
	app := NewApp(engine, db, logger)
	return app, nil
}
