// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Wenell09/lavendera-api/internal/auth/controller"
	"github.com/Wenell09/lavendera-api/internal/auth/repository"
	"github.com/Wenell09/lavendera-api/internal/auth/service"
	"github.com/Wenell09/lavendera-api/internal/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db := NewDB()
	authRepository := repository.NewAuthRepository(db)
	jwtConfig := config.NewJWTConfig()
	logger := config.NewLogger()
	authService := service.NewAuthService(authRepository, jwtConfig, logger)
	validate := config.NewValidator()
	authController := controller.NewAuthController(authService, validate, logger)
	engine := NewRouter(authController, jwtConfig, db, logger)
	app := NewApp(engine, db, logger)
	return app, nil
}

// wire.go:

var AuthWireSet = wire.NewSet(repository.NewAuthRepository, service.NewAuthService, controller.NewAuthController, config.NewValidator, config.NewLogger, config.NewJWTConfig)
